version: '3'

services:
  hadoop:
    image: cloudera/quickstart
    privileged: true
    hostname: quickstart.cloudera
    tty: true
    stdin_open: true
    ports:
      - 8888:8888 # Hue Web UI
      - 10000:10000 # HiveServer2 (for Hive)
      - 9083:9083 # Hive Metastore (for Hive)
      - 14000:14000 # HttpFS (for webhdfs)
      - 50070:50070 # NameNode (for webhdfs)
      - 8020:8020 # NameNode (for uploads)
      - 50075:50075 # DataNode (for uploads)
      - 8021:8021 # JobTracker
      - 50030:50030 # JobTracker
      - 9290:9290 # JobTracker (Thrift Plugin)
      - 10020:10020 # JobHistory Server (int)
      - 19888:19888 # JobHistory Server (ext)
    entrypoint: /usr/bin/docker-quickstart

  oracle:
    image: sath89/oracle-12c
    ports:
      - 1521:1521 # Oracle DB
      - 8080:8080 # Apex Web UI
