version: '3'

services:
  hadoop:
    image: cloudera/quickstart
    privileged: true
    hostname: quickstart.cloudera
    tty: true
    stdin_open: true
    ports:
      - 8888:8888
      - 10000:10000
      - 9083:9083
    entrypoint: /usr/bin/docker-quickstart

  oracle:
    image: sath89/oracle-12c
    ports:
      - 1521:1521
      - 8080:8080
